// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_tumopp
std::string cpp_tumopp(const std::vector<std::string>& args);
RcppExport SEXP tumorr_cpp_tumopp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type args(argsSEXP);
    __result = Rcpp::wrap(cpp_tumopp(args));
    return __result;
END_RCPP
}
