// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tumopp_test
Rcpp::NumericVector tumopp_test(Rcpp::NumericVector x);
RcppExport SEXP tumorr_tumopp_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(tumopp_test(x));
    return __result;
END_RCPP
}
