# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' First example
#' @param args string vector
#' @return string
run_tumopp_raw <- function(args = as.character( c())) {
    .Call('tumorr_run_tumopp_raw', PACKAGE = 'tumorr', args)
}

